config/routes.rb
Rails.application.routes.draw do

resources :expenditures

devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
devise_scope :user do
authenticated :user do
    root 'expenditures#index', as: :authenticated_root
end

  unauthenticated do
   root 'devise/sessions#new', as: :unauthenticated_root

  end
end

  

end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :expenditures
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	devise :omniauthable, :omniauth_providers => [:facebook]

	def self.from_omniauth(auth)
  		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    		user.email = auth.info.email
    		user.password = Devise.friendly_token[0,20]
    	end
    
  	end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
	def index
		@user = current_user
		@expenditures = current_user.expenditures.all
	end

	def create
		@expenditure = Expenditure.new(expenditure_params)
		
		if @expenditure.save
			current_user.expenditures << @expenditure
			current_user.save
			redirect_to expenditures_path
		else
			render 'new'
		end
	end

	def new
		@expenditure = Expenditure.new
	end

	def destroy
		@expenditure = Expenditure.find params[:id]
		@expenditure.destroy

		redirect_to expenditures_path
	end

	private
	def expenditure_params
		params.require(:expenditure).permit(:name, :price)
	end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/expenditures/_form.html.erb
<%= form_for @expenditure do |f| %>
<p>
<%= f.label :name %> <br>
<%= f.text_field :name %>
</p>

<p>
<%= f.label :price %> <br>
<%= f.text_field :price %>
</p>

<p>
<%= f.submit %>
</p>

<% end %>

app/views/expenditures/index.html.erb
<h1>List of all your expenditures!</h1>
<% @user.expenditures.each do |ex| %>
	<strong>Item: </strong> <%= ex.name %> 
	<strong>Price: </strong> <%= ex.price %> <br />
<% end %>

<br /><%= link_to 'Add New Expenditure' , new_expenditure_path(@current_user) %>

app/views/expenditures/new.html.erb
<h1> New Expenditure </h1>

<%=render 'expenditures/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
<% end %>

  <title>BruBudget</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>